### ISSUE TITLE
很久没更新了

### ISSUE THREAD

**Issue by tosslife** [captain-miao/RecyclerViewUtils#1]
这个项目很久没有更新了，不知道这段时间有没有更好的优化呢？
发现几处需要优化的地方：
1.拖住不放会出现列表抖动的情况；
2.建议上拉和下拉进度条分开，上下各一个；
3.回弹效果和拉的不够顺畅；

有时间可否一起优化下

**Comment by captain-miao** [comment]
使用Android5.0 的版本～
RecyclerView的上拉加载更多 https://yanlu.me/recyclerview_pull_up_load_more/
