### ISSUE TITLE
能把 StickyRecyclerHeaderView 和 ExpandableRecyclerHeaderView 结合在一起使用么

### ISSUE THREAD

**Issue by xiaomsh** [captain-miao/RecyclerViewUtils#11]
就是  既能展开，又能下滑的时候 保持头部

**Comment by captain-miao** [comment]
要改写才行~ //不过，我周末才有时间

**Comment by xiaomsh** [comment]
好的

**Comment by captain-miao** [comment]
－，－ 凑合实现了，接口、模型啥的还没好好设计，一个demo版。

大概思路：基于StickyRecyclerHeaderView的实现
1. 保持头部
2. 头部点击，子View展开
3. 子View是需要有父View才能展开、头部也需要父View作为分组，所以写了个不可见的View来当父View。

[demo 例子==》StickyAndExpandableHeadersFragment](https://github.com/captain-miao/RecyclerViewUtils/blob/master/app/src/main/java/com/github/learn/stickyheaders/StickyAndExpandableHeadersFragment.java)
