### ISSUE TITLE
grid extensive testing feature request

### ISSUE THREAD

**Issue by jjhesk** [captain-miao/RecyclerViewUtils#16]
is that possible to make combinations of these items for demo.

header footer grid
grid index
grid header sticky index
grid index
grid header footer index

**Comment by captain-miao** [comment]
这个可以：header footer grid。
其他的，太特殊化，😅，暂不支持吧。
ps :如果确实需要，可以使用RecyclerView，然后ItemView中放几个元素。 🌴

**Comment by jjhesk** [comment]
i tested your case with
header + 2 grid mode
it crashed

**Comment by jjhesk** [comment]
@captain-miao  can i make a PR

**Comment by captain-miao** [comment]
#20
