### ISSUE TITLE
scroll upward 

### ISSUE THREAD

**Issue by jjhesk** [captain-miao/RecyclerViewUtils#18]
added header view in the grid layout manager. it has problem when it scrolling upward after the refresh is pulled. constantly appears. repeating the header view.

**Comment by captain-miao** [comment]
fixed it.

默认是 已经处理了 头部和尾部的情况，占用一行。

你可以同步最新的代码看下，这个例子：HeaderGridRecyclerView。

谢谢你的反馈哈 😄
