### ISSUE TITLE
i will support for Staggeredgridlayoutmanager in my pullrequest

### ISSUE THREAD

**Issue by sungerk** [captain-miao/RecyclerViewUtils#2]

**Comment by captain-miao** [comment]
welcome~ I will release v1.1.8 today

**Comment by sungerk** [comment]
Today  i want to support for Staggeredgridlayoutmanager in my pullrequest , when i checkout you project . I found that you have already achieved this function. that's really a nice open source project

**Comment by captain-miao** [comment]
@sungerk Thank you. I will complete it tonight.
