### ISSUE TITLE
英文环境下自己程序中的@string/app_name被覆盖

### ISSUE THREAD

**Issue by jhpx** [captain-miao/RecyclerViewUtils#4]
由于英文环境下values-en的优先级比values高，资源覆盖顺序会出现如下问题：
RecyclerViewUtils/library/src/main/res/values-en/strings.xml 优先级最高
MyApp/src/main/res/values/strings.xml  优先级次之
RecyclerViewUtils/library/src/main/res/values/strings.xml  优先级最低
结果就是我的app_name变成RALMDemo了。

解决方法也有：就是我自己再定义一个values-en/strings.xml，或者不用app_name这个字串。

不过我想作为一个公用的库，app_name这种常用字符串还是不要占用了吧:)

**Comment by captain-miao** [comment]
－，－ 确实，我重命名掉。
