### ISSUE TITLE
加载超时设置

### ISSUE THREAD

**Issue by godmarvin** [captain-miao/RecyclerViewUtils#9]
大哥，能做个加载超时的功能吗，有些时候没有网络时，会一直在加载状态。顺便问下大哥做android多久了，我还是小弟呢。

**Comment by captain-miao** [comment]
不是我不做啊，应该调用者处理。

网络请求数据处理：
1. 显示加载状态：加载中
2. 发送网络请求
3. 请求响应(不管成功、失败、超时，都进行第4步)
4. 隐藏加载状态：这次加载处理完毕

ps: 我Android开发3年多了...
